language: python

python:
    - 2.6
    - 2.7

env:
    - DJANGO=1.4

install:
    - pip install --use-mirrors -r requirements.txt
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=twingo

after_success:
    - coveralls
