language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO=1.4

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - pip install coveralls

script:
  - python manage.py test

after_success:
  - coveralls
